kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: ${APP_NAME}
  name: grafana-plugins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 1Gi

