apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  labels:
    app: ${APP_NAME}
data:
  GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  GF_SECURITY_ADMIN_USER: ${BASE64_ADMIN_USERNAME}
type: Opaque
