apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  labels:
    app: ${APP_NAME_TELEGRAF}
type: Opaque
stringData:
  INFLUXDB_DB: ${BASE64_INFLUX_DB}
  INFLUXDB_URL: ${INFLUXDB_URL}
  INFLUXDB_USER: ${BASE64_INFLUX_USER}
  INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
