kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: ${APP_NAME_INFLUXDB}
  name: influxdb-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 2Gi

