apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP_NAME_INFLUXDB}
  name: influxdb

spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
  selector:
    app: ${APP_NAME_INFLUXDB}
